services:
  - type: web
    name: god-talk-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /conversations/*
        destination: /index.html
      - type: rewrite
        source: /god
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html 